# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step: 
          name: Build docker-multicontainer App
          services:
            - docker
          script: 
            # Modify the commands below to build your repository.
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            # build the Docker image for API, Worker, Nginx
            - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_API:$BITBUCKET_COMMIT -f Dockerfile.api .
            - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_WORKER:$BITBUCKET_COMMIT -f Dockerfile.worker .
            - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NGINX:$BITBUCKET_COMMIT -f ./docker/nginx/Dockerfile ./docker/nginx
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker images to the Docker registry
            - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_API:$BITBUCKET_COMMIT
            - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_WORKER:$BITBUCKET_COMMIT
            - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NGINX:$BITBUCKET_COMMIT

      - step:
          name: Zip docker-multicontainer App
          script:
          - zip -r $AWS_BS_APP_ZIP_FILENAME *
          artifacts:
          - $AWS_BS_APP_ZIP_FILENAME
      - step:
          name: Deploy to AWS EBS
          caches:
            - pip
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_BS_APP_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_BS_APP_SECRET_KEY
                AWS_DEFAULT_REGION: $AWS_BS_APP_REGION
                APPLICATION_NAME: $AWS_BS_APP_NAME
                ENVIRONMENT_NAME: $AWS_BS_APP_ENVIRONMENT
                ZIP_FILE: $AWS_BS_APP_ZIP_FILENAME
                S3_BUCKET: $AWS_S3_BUCKET
                VERSION_LABEL: $APPLICATION_NAME-$BITBUCKET_BUILD_NUMBER-$BITBUCKET_COMMIT:v.0.2 # Optional.
                # DESCRIPTION: '<string>' # Optional.
                WAIT: 'true'
                # WAIT_INTERVAL: '<integer>' # Optional.
                # COMMAND: '<string>' # Optional.
                DEBUG: 'true' # Optional.
